article_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include("articles.urls")),
]

articles/urls.py
from django.urls import path

from . import views


app_name = "articles"
urlpatterns = [
    path("", views.ArticleListView.as_view(), name="list"),
    path("<int:pk>/<slug:slug>", views.ArticleDetailView.as_view(), name="detail"),
    path("contact-request/add", views.ContactRequestView.as_view(), name="contact_request")
]

articles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=256, default="")
    title_slug = models.SlugField(null=True, blank=True)
    content = models.TextField(blank=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    publication_date = models.DateTimeField(null=True, blank=True)
    is_published = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.title_slug = slugify(self.title)
        if self.is_published:
            self.publication_date = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title_slug


class ContactRequest(models.Model):
    email = models.EmailField(null=False, blank=False)
    name = models.CharField(max_length=256)
    content = models.TextField(null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)

articles/forms.py
from django.forms import ModelForm

from .models import ContactRequest


class ContactRequestForm(ModelForm):
    class Meta:
        model = ContactRequest
        fields = ["email", "name", "content"]

articles/views.py
from django.views.generic import ListView, DetailView, FormView
from django.urls import reverse_lazy
from django.core.mail import send_mail
from django.conf import settings

from .forms import ContactRequestForm
from .models import Article


class ArticleListView(ListView):
    model = Article
    paginate_by = 5
    template_name = "index.html"
    queryset = Article.objects.filter(is_published=True)


class ArticleDetailView(DetailView):
    model = Article
    template_name = "details.html"
    slug_field = "title_slug"


class ContactRequestView(FormView):
    form_class = ContactRequestForm
    template_name = "contact_request.html"
    success_url = reverse_lazy("articles:list")

    def form_valid(self, form):
        form.save()
        if not settings.DEBUG:
            send_mail(
                subject=form.cleaned_data["name"],
                message=form.cleaned_data["content"],
                from_email=f"Reply-to{form.cleaned_data['email']}",
                recipient_list=[settings.EMAIL_DESTINATION],
                fail_silently=False
            )
        return super().form_valid(form)

articles/templates/contact_request.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Send" />
</form>
</body>
</html>

articles/templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{{ article.title }}</title>
</head>
<body>
  <p>Title: {{ article.title }}</p>
  <p>{{ article.content }}</p>
  <p>Published on: {{ article.publication_date }}</p>
  <p>Written by: {{ article.author.get_full_name }}</p>
  <a href="{% url 'articles:list' %}">Back to Index</a>
</body>
</html>

articles/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Articles</title>
</head>
<body>
  <a href="{% url 'articles:contact_request' %}">Create contact request</a>
  {% if object_list %}
    <ul>
      {% for article in object_list %}
      <li>
        <a href="{% url 'articles:detail' pk=article.pk slug=article.title_slug %}">{{ article.title }}</a>
      </li>
      {% endfor %}
    </ul>

    <div class="pagination">
      <span class="step-links">
        {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
        <br />
        {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
      </span>
    </div>
  {% endif %}
</body>
</html>